name: Build and Push Database Docker Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile.database'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-db

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Dockerfile.db
      run: |
        cp Dockerfile.database Dockerfile.db
        echo "# Clerk" >> Dockerfile.db
        echo "ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.CLERK_PUBLISHABLE_KEY }}" >> Dockerfile.db
        echo "ENV CLERK_SECRET_KEY=\"\"" >> Dockerfile.db
        echo "ENV CLERK_WEBHOOK_SECRET=${{ secrets.CLERK_WEBHOOK_SECRET }}" >> Dockerfile.db

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile.db
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

    - name: Clean up
      if: always()
      run: rm -f Dockerfile.db
